-- Tender Pack schema and seed (generated by: python tender_seed.py)
-- Safe to re-run: creates tables only if missing; inserts each seed answer only if its answerId is absent.

IF OBJECT_ID('dbo.tender_answer', 'U') IS NULL
CREATE TABLE dbo.tender_answer (
    answerId     NVARCHAR(100)  NOT NULL PRIMARY KEY,
    category     NVARCHAR(200)  NOT NULL,
    question     NVARCHAR(2000) NOT NULL,
    keywords     NVARCHAR(MAX)  NOT NULL,  -- JSON array
    answerText   NVARCHAR(MAX)  NOT NULL,
    evidence     NVARCHAR(MAX)  NOT NULL,  -- JSON array of Policy & Compliance title keys
    owner        NVARCHAR(400)  NOT NULL,
    status       NVARCHAR(50)   NOT NULL,  -- Draft | Approved | Retired
    reviewDate   DATE           NULL,
    approvedBy   NVARCHAR(400)  NULL,
    approvedAt   DATETIME2      NULL,
    updatedBy    NVARCHAR(400)  NULL,
    updatedAt    DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('dbo.tender_pack', 'U') IS NULL
CREATE TABLE dbo.tender_pack (
    packId       NVARCHAR(64)   NOT NULL PRIMARY KEY,
    packRef      NVARCHAR(64)   NOT NULL,
    clientName   NVARCHAR(400)  NOT NULL,
    bidReference NVARCHAR(400)  NULL,
    deadline     DATE           NOT NULL,
    preparedBy   NVARCHAR(400)  NOT NULL,
    createdAt    DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME(),
    summary      NVARCHAR(MAX)  NOT NULL,  -- JSON: counts by status
    snapshot     NVARCHAR(MAX)  NOT NULL   -- JSON: the full pack exactly as issued (audit record)
);

IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'cert-cyber-essentials-plus')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'cert-cyber-essentials-plus', N'Certifications', N'Do you hold Cyber Essentials Plus certification?', N'["cyber essentials plus", "ce+", "ce plus", "certification", "certified", "independently assessed"]', N'Yes. Cognition Learning Group holds Cyber Essentials Plus certification, which is independently assessed and verified against the UK Government''s Cyber Essentials scheme. A copy of the current certificate is included in the evidence appendix.', N'["Cyber Essentials Plus"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'cert-cyber-essentials')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'cert-cyber-essentials', N'Certifications', N'Do you hold Cyber Essentials certification?', N'["cyber essentials", "certification", "certified", "government scheme", "basic controls"]', N'Yes. Cognition Learning Group holds Cyber Essentials certification under the UK Government''s Cyber Essentials scheme. A copy of the current certificate is included in the evidence appendix.', N'["Cyber Essentials"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'cert-iso-27001')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'cert-iso-27001', N'Certifications', N'Are you certified to ISO/IEC 27001?', N'["iso 27001", "iso/iec 27001", "27001", "iso", "isms certification", "accredited"]', N'Our information security management system and policy set (CLG_SEC_POL_001 to CLG_SEC_POL_006) are aligned with ISO/IEC 27001:2022 and approved by the CLG Board of Directors. [confirm: state whether CLG holds ISO/IEC 27001 certification, and if not, any planned certification date.]', N'["CLG_SEC_POL_001"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'gov-information-security-policy')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'gov-information-security-policy', N'Governance', N'Do you have a documented information security policy?', N'["information security policy", "security policy", "isms", "isms policy", "governance framework"]', N'Yes. Information security is governed by the CLG Information Security Management System (ISMS) Policy, CLG_SEC_POL_001, supported by policies CLG_SEC_POL_002 to CLG_SEC_POL_006. The policy set is aligned with ISO/IEC 27001:2022, approved by the CLG Board of Directors, and owned by the Group Director, IT and Digital Transformation. Each policy carries a scheduled review date.', N'["CLG_SEC_POL_001"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'gov-security-responsibility')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'gov-security-responsibility', N'Governance', N'Who is responsible for information security in your organisation?', N'["responsible", "responsibility", "accountable", "owner", "security lead", "ciso", "roles"]', N'Overall accountability for information security sits with the CLG Board of Directors, which approves the information security policy set. Day-to-day ownership sits with the Group Director, IT and Digital Transformation, who owns the ISMS Policy (CLG_SEC_POL_001).', N'["CLG_SEC_POL_001"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'dp-ico-registration')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'dp-ico-registration', N'Data protection', N'Are you registered with the Information Commissioner''s Office (ICO)?', N'["ico", "information commissioner", "registered", "registration", "data protection fee"]', N'Yes. Cognition Education UK Limited is registered with the Information Commissioner''s Office under registration reference ZA211766.', N'["ICO"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'dp-uk-gdpr')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'dp-uk-gdpr', N'Data protection', N'How do you comply with UK GDPR and the Data Protection Act 2018?', N'["gdpr", "uk gdpr", "data protection act", "personal data", "privacy", "dpa", "lawful"]', N'Cognition Education UK Limited is registered with the ICO (ZA211766) and processes personal data under its Board-approved information security policies. Staff may only store or process personal or sensitive data in CLG''s approved applications. [confirm: name the Data Protection Officer or data protection lead and how data subject requests are handled.]', N'["ICO", "CLG_SEC_POL_001"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'access-mfa')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'access-mfa', N'Access control', N'Do you use multi-factor authentication?', N'["mfa", "multi-factor", "multifactor", "2fa", "two-factor", "authentication", "sign-in"]', N'Yes. Staff sign in with Microsoft Entra ID accounts. [confirm: multi-factor authentication is enforced for all staff accounts through Entra Conditional Access, including administrators and remote access.]', N'["CLG_SEC_POL_001", "Cyber Essentials"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'access-control')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'access-control', N'Access control', N'How do you control access to systems and data?', N'["access control", "least privilege", "permissions", "role-based", "joiners", "leavers", "leave", "offboarding", "restrict", "privileged"]', N'Access to CLG systems is controlled through Microsoft Entra ID, with access granted by role and security group. [confirm: describe the joiner, mover and leaver process, how often access is reviewed, and how administrator accounts are separated from day-to-day accounts.]', N'["CLG_SEC_POL_001"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'device-management')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'device-management', N'Devices', N'How are laptops and mobile devices secured?', N'["laptop", "device", "endpoint", "mobile", "intune", "encryption", "mdm", "asset"]', N'Corporate devices are managed through Microsoft Intune and recorded in the CLG IT Asset Register, which is reconciled against Intune. [confirm: full-disk encryption standard (for example BitLocker or FileVault), screen-lock policy, and remote wipe for lost or stolen devices.]', N'["Cyber Essentials"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'malware-patching')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'malware-patching', N'Devices', N'How do you protect against malware and keep systems patched?', N'["malware", "antivirus", "anti-virus", "patch", "patching", "updates", "vulnerability"]', N'Malware protection and security updates are covered by the Cyber Essentials controls CLG is certified against. [confirm: the anti-malware product in use (for example Microsoft Defender) and the target time to apply critical security updates.]', N'["Cyber Essentials"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'incident-response')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'incident-response', N'Incident management', N'Do you have a process for responding to security incidents and data breaches?', N'["incident", "breach", "response", "report", "notify", "72 hours", "security event"]', N'Security incidents are reported to the IT team through the CLG IT helpdesk and handled under CLG''s information security policies. Personal data breaches that meet the legal threshold are reported to the ICO within 72 hours. [confirm: name the incident response policy and the client notification commitment you are prepared to offer.]', N'["CLG_SEC_POL_001"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'business-continuity')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'business-continuity', N'Resilience', N'Do you have a business continuity and disaster recovery plan?', N'["business continuity", "bcp", "disaster recovery", "dr", "resilience", "recovery"]', N'Yes. CLG maintains a Business Continuity Plan. [confirm: the approved version and date, how often it is tested, and the recovery time objectives you are prepared to state.]', N'[]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'hosting-backup')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'hosting-backup', N'Resilience', N'Where is your data hosted and how is it backed up?', N'["hosted", "hosting", "data centre", "data center", "cloud", "backup", "backed up", "stored", "storage", "residency"]', N'CLG''s core systems run on Microsoft 365 and Microsoft Azure; CLG''s own Azure services are hosted in the UK South region. [confirm: Microsoft 365 data residency, backup approach and retention period.]', N'[]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'staff-training')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'staff-training', N'People', N'Do your staff receive information security awareness training?', N'["training", "awareness", "staff", "phishing", "induction", "education"]', N'[confirm: describe security awareness training — at induction and how often after, the platform used, and whether phishing simulations are run.]', N'["CLG_SEC_POL_001"]', N'IT Security', N'Draft', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = N'supplier-security')
INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) VALUES (N'supplier-security', N'Suppliers', N'How do you manage information security risks from suppliers and subcontractors?', N'["supplier", "suppliers", "third party", "subcontractor", "vendor", "supply chain"]', N'[confirm: describe how suppliers that handle CLG or client data are assessed before use and reviewed, and whether contracts include security and data protection terms.]', N'["CLG_SEC_POL_001"]', N'IT Security', N'Draft', NULL);
