"""
IT Helpdesk Portal — Tender Pack seed answer library (Batch I, HD-054–058 widened)
==================================================================================
The single source of the starter answer library. InMemoryTenderStore loads
it directly, and schema_and_seed_tender.sql is generated from it
(python tender_seed.py > schema_and_seed_tender.sql), so a fresh database and
the offline tests always hold the same rows.

*** EVERY SEED ANSWER IS A DRAFT ***
Only facts already verified in the Policy & Compliance hub are stated as
fact (the CLG_SEC_POL_001-006 policy set, the Board approval, the owner role,
Cyber Essentials / Cyber Essentials Plus, ICO registration ZA211766). Anything
not yet verified is written as a [confirm: ...] placeholder. The matcher
treats any answer containing "[confirm" as needing review, so a placeholder
can never reach a client without a person replacing it.

evidence = keys resolved against live Policy & Compliance records at match
time (exact title first, then "title starts with key", shortest wins), so
"Cyber Essentials" never resolves to "Cyber Essentials Plus".
"""

from tender_library_v2 import LIBRARY_V2

# v2 (2 Oct 2026): 108 answers written from the policy documents themselves —
# see tender_library_v2.py for sources and writing rules. The original 16 seed
# ids are kept, so links and any edits made to them in the portal still apply.
SEED_ANSWERS = [
    {"answerId": aid, "category": cat, "question": q, "keywords": list(kw), "answerText": text, "evidence": list(ev)}
    for (aid, cat, q, kw, text, ev) in LIBRARY_V2
]

# Business Continuity Plan, added to Policy & Compliance as a Policy record so
# answers can cite it. Values taken from the document (March 2026, document
# control entry 12 of 19 Mar 2026, owner CFO supported by CEO, annual review).
BCP_RECORD = {
    "title": "CLG Business Continuity Plan and Cyber Security Policy",
    "currentVersion": "V10.4 (March 2026)",
    "approvalStatus": "Annual review 19 Mar 2026; tested March 2026, all RTO/RPO tests passed. Owner: CFO, supported by the CEO.",
    "nextReviewDate": "2027-03-19",
    "confidentialityLevel": "Confidential",
}


def _sql_str(value):
    if value is None:
        return "NULL"
    return "N'" + str(value).replace("'", "''") + "'"


def render_sql() -> str:
    """Schema + idempotent seed for Azure SQL. Seed rows are inserted per
    row only when that answerId is absent (never a blanket IF NOT EXISTS),
    so re-running never overwrites answers IT Security has since edited."""
    import json
    out = [
        "-- Tender Pack schema and seed (generated by: python tender_seed.py)",
        "-- Safe to re-run: creates tables only if missing, adds new answers, refreshes only untouched seed answers,",
        "-- adds the BCP once, and corrects the ICO expiry only if it still holds the wrong date.",
        "",
        "IF OBJECT_ID('dbo.tender_answer', 'U') IS NULL",
        "CREATE TABLE dbo.tender_answer (",
        "    answerId     NVARCHAR(100)  NOT NULL PRIMARY KEY,",
        "    category     NVARCHAR(200)  NOT NULL,",
        "    question     NVARCHAR(2000) NOT NULL,",
        "    keywords     NVARCHAR(MAX)  NOT NULL,  -- JSON array",
        "    answerText   NVARCHAR(MAX)  NOT NULL,",
        "    evidence     NVARCHAR(MAX)  NOT NULL,  -- JSON array of Policy & Compliance title keys",
        "    owner        NVARCHAR(400)  NOT NULL,",
        "    status       NVARCHAR(50)   NOT NULL,  -- Draft | Approved | Retired",
        "    reviewDate   DATE           NULL,",
        "    approvedBy   NVARCHAR(400)  NULL,",
        "    approvedAt   DATETIME2      NULL,",
        "    updatedBy    NVARCHAR(400)  NULL,",
        "    updatedAt    DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME()",
        ");",
        "",
        "IF OBJECT_ID('dbo.tender_pack', 'U') IS NULL",
        "CREATE TABLE dbo.tender_pack (",
        "    packId       NVARCHAR(64)   NOT NULL PRIMARY KEY,",
        "    packRef      NVARCHAR(64)   NOT NULL,",
        "    clientName   NVARCHAR(400)  NOT NULL,",
        "    bidReference NVARCHAR(400)  NULL,",
        "    deadline     DATE           NOT NULL,",
        "    preparedBy   NVARCHAR(400)  NOT NULL,",
        "    createdAt    DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME(),",
        "    summary      NVARCHAR(MAX)  NOT NULL,  -- JSON: counts by status",
        "    snapshot     NVARCHAR(MAX)  NOT NULL   -- JSON: the full pack exactly as issued (audit record)",
        ");",
        "",
    ]
    out += [
        "-- ---------------------------------------------------------------------------",
        "-- Answer library v2: insert new answers; refresh seed answers nobody has edited",
        "-- (updatedBy and approvedBy both NULL). Answers edited or approved in the",
        "-- portal are never overwritten.",
        "-- ---------------------------------------------------------------------------",
    ]
    for a in SEED_ANSWERS:
        vals = {
            "id": _sql_str(a["answerId"]), "cat": _sql_str(a["category"]), "q": _sql_str(a["question"]),
            "kw": _sql_str(json.dumps(a["keywords"])), "txt": _sql_str(a["answerText"]), "ev": _sql_str(json.dumps(a["evidence"])),
        }
        out.append(f"IF NOT EXISTS (SELECT 1 FROM dbo.tender_answer WHERE answerId = {vals['id']})")
        out.append(
            "    INSERT INTO dbo.tender_answer (answerId, category, question, keywords, answerText, evidence, owner, status, reviewDate) "
            f"VALUES ({vals['id']}, {vals['cat']}, {vals['q']}, {vals['kw']}, {vals['txt']}, {vals['ev']}, N'IT Security', N'Draft', NULL);"
        )
        out.append("ELSE")
        out.append(
            f"    UPDATE dbo.tender_answer SET category = {vals['cat']}, question = {vals['q']}, keywords = {vals['kw']}, "
            f"answerText = {vals['txt']}, evidence = {vals['ev']}, updatedAt = SYSUTCDATETIME() "
            f"WHERE answerId = {vals['id']} AND updatedBy IS NULL AND approvedBy IS NULL;"
        )
    b = BCP_RECORD
    out += [
        "",
        "-- ---------------------------------------------------------------------------",
        "-- Policy & Compliance: add the Business Continuity Plan (once, matched by name)",
        "-- ---------------------------------------------------------------------------",
        f"IF NOT EXISTS (SELECT 1 FROM dbo.ci_base WHERE name = {_sql_str(b['title'])})",
        "BEGIN",
        "    DECLARE @bcp TABLE (ciId UNIQUEIDENTIFIER);",
        "    INSERT INTO dbo.ci_base (ciClass, name, status, owner, entity) OUTPUT INSERTED.ciId INTO @bcp",
        f"    VALUES (N'Document', {_sql_str(b['title'])}, N'Active', N'CFO', N'Cognition Learning Group');",
        "    INSERT INTO dbo.document_metadata (ciId, documentType, currentVersion, approvalStatus, nextReviewDate, confidentialityLevel, documentUrl)",
        f"    SELECT ciId, N'Policy', {_sql_str(b['currentVersion'])}, {_sql_str(b['approvalStatus'])}, {_sql_str(b['nextReviewDate'])}, {_sql_str(b['confidentialityLevel'])}, NULL FROM @bcp;",
        "END;",
        "",
        "-- ---------------------------------------------------------------------------",
        "-- Correct the ICO registration expiry: the certificate (ZA211766) states",
        "-- 'Registration expires: 15 October 2027'; the portal held 2026-10-15.",
        "-- ---------------------------------------------------------------------------",
        "UPDATE dm SET dm.expiryDate = '2027-10-15', dm.updatedAt = SYSUTCDATETIME()",
        "FROM dbo.document_metadata dm JOIN dbo.ci_base cb ON cb.ciId = dm.ciId",
        "WHERE dm.documentType = N'Certificate' AND cb.name LIKE N'ICO%' AND dm.expiryDate = '2026-10-15';",
        "",
        "-- Check: should return the BCP row and the ICO row with expiryDate 2027-10-15.",
        "SELECT cb.name, dm.documentType, dm.currentVersion, dm.nextReviewDate, dm.expiryDate",
        "FROM dbo.document_metadata dm JOIN dbo.ci_base cb ON cb.ciId = dm.ciId",
        f"WHERE cb.name = {_sql_str(b['title'])} OR cb.name LIKE N'ICO%';",
        "SELECT status, COUNT(*) AS answers FROM dbo.tender_answer GROUP BY status;",
    ]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    print(render_sql(), end="")
